name: Issue to Database Commit

on:
  issues:
    types:
      - opened

jobs:
  process-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: database

      - name: Extract JSON from issue body
        id: extract-json
        run: |
          BODY="${{ github.event.issue.body }}"
          JSON=$(echo "$BODY" | sed -n '/```json/,/```/p' | sed '1d;$d')
          
          if [ -z "$JSON" ]; then
            echo "Error: No JSON detected in issue body."
            exit 1
          fi
          
          ENCODED_JSON=$(echo "$JSON" | base64 -w 0)
          echo "json=$ENCODED_JSON" >> $GITHUB_ENV

      - name: Parse JSON and prepare file
        id: parse-json
        run: |
          DECODED_JSON=$(echo "$json" | base64 -d)
          echo "$DECODED_JSON" > issue_data.json
      
          PLAYFAB_ID=$(jq -r '.PlayfabID' issue_data.json)
          GUID=$(jq -r '.GUID' issue_data.json)
          NAME=$(jq -r '.Name' issue_data.json)
      
          if [[ -z "$PLAYFAB_ID" || -z "$GUID" || -z "$NAME" ]]; then
            echo "Error: Missing required JSON fields."
            exit 1
          fi
      
          echo "PlayfabID: $PLAYFAB_ID"
          echo "GUID: $GUID"
          echo "Name: $NAME"
      
          echo "playfab_id=$PLAYFAB_ID" >> $GITHUB_ENV
          echo "guid=$GUID" >> $GITHUB_ENV
          echo "name=$NAME" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          README_FILE="data/README.md"
          ENTRY="- **$NAME** ($GUID)"
          
          if [ ! -f "$README_FILE" ]; then
            echo "# Database Records" > "$README_FILE"
          fi
          
          if ! grep -q "$GUID" "$README_FILE"; then
            echo "$ENTRY" >> "$README_FILE"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add data for ${{ env.name }} (${{ env.guid }})"
          git push origin database
