name: Issue to Database Commit

on:
  issues:
    types:
      - opened

jobs:
  process-issue:
    runs-on: ubuntu-latest
    outputs:
      json_payload: ${{ steps.extract-json.outputs.payload }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: database

      - name: Extract JSON from issue body
        id: extract-json
        run:
          ./.github/workflows/scripts/extract-issue-from-json-body.sh "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Parse JSON and prepare file
        id: parse-json
        run: |
          PLAYFAB_ID="${{ fromJson(steps.extract-json.outputs.payload).PlayfabID }}"
          GUID="${{ fromJson(steps.extract-json.outputs.payload).GUID }}"
          NAME="${{ fromJson(steps.extract-json.outputs.payload).Name }}"
      
          if [[ -z "$PLAYFAB_ID" || -z "$GUID" || -z "$NAME" ]]; then
            echo "Error: Missing required JSON fields."
            exit 1
          fi
      
          echo "PlayfabID: $PLAYFAB_ID"
          echo "GUID: $GUID"
          echo "Name: $NAME"
      
          echo "playfab_id=$PLAYFAB_ID" >> $GITHUB_ENV
          echo "guid=$GUID" >> $GITHUB_ENV
          echo "name=$NAME" >> $GITHUB_ENV

      - name: Create JSON file
        run: |
          JSON_FILE="data/${{ env.playfab_id }}/${{ env.guid }}.json"
          mkdir -p "$(dirname "$JSON_FILE")"
          echo '${{ steps.extract-json.outputs.payload }}' > "$JSON_FILE"
          echo "Created JSON file at $JSON_FILE"

      - name: Update README.md
        run: |
          README_FILE="data/${{ env.playfab_id }}/README.md"
          mkdir -p "$(dirname "$README_FILE")"  # Ensure directory exists
          ENTRY="- **${{ env.name }}** (${{ env.guid }})"
          
          if [ ! -f "$README_FILE" ]; then
            echo "# Database Records" > "$README_FILE"
          fi
          
          if ! grep -q "${{ env.guid }}" "$README_FILE"; then
            echo "$ENTRY" >> "$README_FILE"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add data for ${{ env.name }} (${{ env.guid }})"
          git push origin database
